"use client";

import { useEffect, useCallback, useRef, useState } from "react";
import { DriveFile } from "@/lib/drive/types";
import { driveImageUrl, driveDownloadUrl } from "@/lib/drive/public-url";
import { useLanguage } from "@/lib/i18n";

interface Props {
  photos: DriveFile[];
  activeIndex: number;
  favorites: Set<string>;
  allowDownload?: boolean;
  onClose: () => void;
  onNext: () => void;
  onPrev: () => void;
  onToggleFavorite: (photoId: string) => void;
}

export function Lightbox({ photos, activeIndex, favorites, allowDownload = true, onClose, onNext, onPrev, onToggleFavorite }: Props) {
  const { t } = useLanguage();
  const g = t.gallery;
  const photo = photos[activeIndex];
  const thumbsRef = useRef<HTMLDivElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [isFullscreen, setIsFullscreen] = useState(false);
  // Track image load so we show a spinner instead of a black screen while the
  // full-size preview is still being fetched/generated by Drive.
  const [imgLoaded, setImgLoaded] = useState(false);
  // Slideshow: auto-advances every 4s. Spacebar toggles it; it auto-stops at
  // the last photo so a gallery doesn't loop forever in a forgotten tab.
  const [playing, setPlaying] = useState(false);
  const slideRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    setImgLoaded(false);
  }, [activeIndex]);

  // Slideshow interval — started/stopped by the `playing` state. When playing
  // reaches the last photo, it auto-stops. The interval is cleared on any
  // manual navigation (activeIndex changes) and re-created so the 4s timer
  // resets after each advance, giving each photo a full 4 seconds.
  useEffect(() => {
    if (!playing) {
      if (slideRef.current) clearInterval(slideRef.current);
      return;
    }
    if (activeIndex >= photos.length - 1) {
      // Reached the end while playing — stop, don't loop.
      setPlaying(false);
      return;
    }
    slideRef.current = setInterval(() => {
      onNext();
    }, 4000);
    return () => {
      if (slideRef.current) clearInterval(slideRef.current);
    };
  }, [playing, activeIndex, photos.length, onNext]);

  // Preload the next and previous full-size images so navigating feels instant
  // (the browser caches them in the background while you view the current one).
  useEffect(() => {
    for (const i of [activeIndex + 1, activeIndex - 1]) {
      const p = photos[i];
      if (p && !p.mimeType.startsWith("video/")) {
        const img = new window.Image();
        img.src = driveImageUrl(p, 2048);
      }
    }
  }, [activeIndex, photos]);

  function toggleFullscreen() {
    if (!document.fullscreenElement) {
      containerRef.current?.requestFullscreen();
    } else {
      document.exitFullscreen();
    }
  }

  useEffect(() => {
    const handler = () => setIsFullscreen(!!document.fullscreenElement);
    document.addEventListener("fullscreenchange", handler);
    return () => document.removeEventListener("fullscreenchange", handler);
  }, []);

  const handleKey = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === "Escape" && !document.fullscreenElement) onClose();
      if (e.key === "ArrowRight") onNext();
      if (e.key === "ArrowLeft") onPrev();
      if (e.key === "f" || e.key === "F") toggleFullscreen();
      // Spacebar toggles the slideshow. preventDefault stops the page from
      // scrolling (the lightbox already locks body overflow, but a button might
      // be focused and would otherwise get a click on space).
      if (e.key === " ") {
        e.preventDefault();
        setPlaying((v) => !v);
      }
    },
    [onClose, onNext, onPrev]
  );

  useEffect(() => {
    document.addEventListener("keydown", handleKey);
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", handleKey);
      document.body.style.overflow = "";
    };
  }, [handleKey]);

  // Scroll active thumbnail into view
  useEffect(() => {
    if (thumbsRef.current) {
      const active = thumbsRef.current.querySelector("[data-active='true']") as HTMLElement;
      active?.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "center" });
    }
  }, [activeIndex]);

  if (!photo) return null;

  const isFavorited = favorites.has(photo.id);

  return (
    <div ref={containerRef} className="fixed inset-0 z-50 bg-black/98 flex flex-col animate-fade-in">
      {/* Top bar */}
      <div className="flex items-center justify-between px-5 py-4 shrink-0">
        {/* Counter */}
        <span className="text-white/50 text-sm">
          {activeIndex + 1} <span className="text-white/25">/</span> {photos.length}
        </span>

        {/* Actions */}
        <div className="flex items-center gap-2">
          {/* Slideshow play/pause */}
          <button
            onClick={() => setPlaying((v) => !v)}
            title={g.slideshow}
            className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-medium transition-all ${
              playing
                ? "bg-[#17509e] text-white"
                : "bg-white/10 text-white/70 hover:bg-white/20"
            }`}
          >
            {playing ? (
              <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 24 24">
                <path d="M6 5h4v14H6zM14 5h4v14h-4z" />
              </svg>
            ) : (
              <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 24 24">
                <path d="M8 5.14v14l11-7-11-7z" />
              </svg>
            )}
            {g.slideshow}
          </button>

          {/* Favorite */}
          <button
            onClick={() => onToggleFavorite(photo.id)}
            className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-medium transition-all ${
              isFavorited
                ? "bg-[#17509e] text-white"
                : "bg-white/10 text-white/70 hover:bg-white/20"
            }`}
          >
            <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill={isFavorited ? "currentColor" : "none"} stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
            </svg>
            {g.favorite}
          </button>

          {/* Download */}
          {allowDownload && (
            <a
              href={driveDownloadUrl(photo.id)}
              download={photo.name}
              onClick={(e) => e.stopPropagation()}
              className="flex items-center gap-1.5 bg-white/10 hover:bg-white/20 text-white/70 hover:text-white rounded-full px-3 py-1.5 text-xs font-medium transition-all"
            >
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              {g.download}
            </a>
          )}

          {/* Fullscreen */}
          <button
            onClick={toggleFullscreen}
            title={g.fullscreen}
            className="w-8 h-8 flex items-center justify-center bg-white/10 hover:bg-white/20 text-white/70 hover:text-white rounded-full transition-all"
          >
            {isFullscreen ? (
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 9V4.5M9 9H4.5M9 9L3.75 3.75M9 15v4.5M9 15H4.5M9 15l-5.25 5.25M15 9h4.5M15 9V4.5M15 9l5.25-5.25M15 15h4.5M15 15v4.5m0-4.5l5.25 5.25" />
              </svg>
            ) : (
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" />
              </svg>
            )}
          </button>

          {/* Close */}
          <button
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center bg-white/10 hover:bg-white/20 text-white/70 hover:text-white rounded-full transition-all"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>

      {/* Main image area */}
      <div
        className="flex-1 flex items-center justify-center relative px-2 sm:px-14 min-h-0"
        onClick={onClose}
      >
        {/* Prev */}
        {activeIndex > 0 && (
          <button
            className="absolute left-3 top-1/2 -translate-y-1/2 w-10 h-10 flex items-center justify-center bg-white/10 hover:bg-white/20 text-white rounded-full transition-all z-10 hover:scale-110"
            onClick={(e) => { e.stopPropagation(); onPrev(); }}
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
            </svg>
          </button>
        )}

        {/* Image or Video */}
        <div onClick={(e) => e.stopPropagation()} className="max-w-5xl max-h-full w-full flex items-center justify-center relative">
          {photo.mimeType.startsWith("video/") ? (
            // Play the video straight from Google Drive's own player (no bytes
            // through our server). Keeps video off Vercel bandwidth.
            <iframe
              key={photo.id}
              src={`https://drive.google.com/file/d/${photo.id}/preview`}
              allow="autoplay; fullscreen"
              allowFullScreen
              className="w-full max-w-4xl aspect-video max-h-[75vh] rounded-lg shadow-2xl animate-scale-in border-0"
            />
          ) : (
            <>
              {!imgLoaded && (
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                  <div className="w-8 h-8 border-2 border-white/20 border-t-white/80 rounded-full animate-spin" />
                </div>
              )}
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                key={photo.id}
                src={driveImageUrl(photo, 2048)}
                alt={photo.name}
                fetchPriority="high"
                decoding="async"
                onLoad={() => setImgLoaded(true)}
                onError={(e) => {
                  const img = e.currentTarget;
                  if (!img.dataset.fallback) {
                    img.dataset.fallback = "1";
                    img.src = `/api/photos/proxy?fileId=${photo.id}&size=preview`;
                  } else {
                    setImgLoaded(true);
                  }
                }}
                className={`max-w-full max-h-[75vh] object-contain rounded-lg shadow-2xl animate-scale-in transition-opacity duration-300 ${imgLoaded ? "opacity-100" : "opacity-0"}`}
              />
            </>
          )}
        </div>

        {/* Next */}
        {activeIndex < photos.length - 1 && (
          <button
            className="absolute right-3 top-1/2 -translate-y-1/2 w-10 h-10 flex items-center justify-center bg-white/10 hover:bg-white/20 text-white rounded-full transition-all z-10 hover:scale-110"
            onClick={(e) => { e.stopPropagation(); onNext(); }}
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
            </svg>
          </button>
        )}
      </div>

      {/* Thumbnail strip */}
      <div className="shrink-0 pb-4 pt-3">
        <div
          ref={thumbsRef}
          className="flex gap-1.5 overflow-x-auto px-4 pb-1"
          style={{ scrollbarWidth: "none" }}
        >
          {photos.map((p, i) => (
            <button
              key={p.id}
              data-active={i === activeIndex ? "true" : "false"}
              onClick={() => {
                if (i < activeIndex) {
                  for (let j = activeIndex; j > i; j--) onPrev();
                } else {
                  for (let j = activeIndex; j < i; j++) onNext();
                }
              }}
              className={`shrink-0 w-14 h-14 rounded-lg overflow-hidden transition-all ${
                i === activeIndex
                  ? "ring-2 ring-white opacity-100 scale-105"
                  : "opacity-40 hover:opacity-70"
              }`}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={driveImageUrl(p, 150)}
                alt=""
                loading="lazy"
                onError={(e) => {
                  // If Google's CDN throttles/fails, fall back to our proxy once.
                  const img = e.currentTarget;
                  if (!img.dataset.fallback) {
                    img.dataset.fallback = "1";
                    img.src = `/api/photos/proxy?fileId=${p.id}&size=thumb`;
                  }
                }}
                className="w-full h-full object-cover"
              />
              {favorites.has(p.id) && (
                <div className="absolute top-0.5 right-0.5 w-3 h-3 bg-[#17509e] rounded-full" />
              )}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
